// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx_bfqZdVopPMjJD7yIsyDFhPTLoIRSO4',
    appId: '1:580850132245:web:6b74834fe39b556bc0751c',
    messagingSenderId: '580850132245',
    projectId: 'dhristitech-notes',
    authDomain: 'dhristitech-notes.firebaseapp.com',
    storageBucket: 'dhristitech-notes.firebasestorage.app',
    measurementId: 'G-2B0Y8N6E9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhddJIh5_suHtSfl-8XMVq1-Ty7q-WJdk',
    appId: '1:580850132245:android:b11248250adc3c5fc0751c',
    messagingSenderId: '580850132245',
    projectId: 'dhristitech-notes',
    storageBucket: 'dhristitech-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4kXAPfc-SNbkK4SgEZmshBaZGgc_Gu-0',
    appId: '1:580850132245:ios:246db6b4094e2d50c0751c',
    messagingSenderId: '580850132245',
    projectId: 'dhristitech-notes',
    storageBucket: 'dhristitech-notes.firebasestorage.app',
    iosBundleId: 'com.example.dristiTech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4kXAPfc-SNbkK4SgEZmshBaZGgc_Gu-0',
    appId: '1:580850132245:ios:246db6b4094e2d50c0751c',
    messagingSenderId: '580850132245',
    projectId: 'dhristitech-notes',
    storageBucket: 'dhristitech-notes.firebasestorage.app',
    iosBundleId: 'com.example.dristiTech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx_bfqZdVopPMjJD7yIsyDFhPTLoIRSO4',
    appId: '1:580850132245:web:17c3417c8fd3a6f7c0751c',
    messagingSenderId: '580850132245',
    projectId: 'dhristitech-notes',
    authDomain: 'dhristitech-notes.firebaseapp.com',
    storageBucket: 'dhristitech-notes.firebasestorage.app',
    measurementId: 'G-MCTBE8QBFX',
  );
}
