// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKjsgxNOKHSrH_8LoY2x5IiZaLk2oh0rk',
    appId: '1:285056131909:web:78e66d2510990bcdc4d42c',
    messagingSenderId: '285056131909',
    projectId: 'edupro-app-daa1b',
    authDomain: 'edupro-app-daa1b.firebaseapp.com',
    storageBucket: 'edupro-app-daa1b.firebasestorage.app',
    measurementId: 'G-1T2MS4YKH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJjHw6ppVJ6zn2P-bEv4dVBFNvdDtGxYM',
    appId: '1:285056131909:android:0cec32467103ff93c4d42c',
    messagingSenderId: '285056131909',
    projectId: 'edupro-app-daa1b',
    storageBucket: 'edupro-app-daa1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY8QbyGTq76A9BCmhjCRQz_infa-GMPU',
    appId: '1:285056131909:ios:1e3762d7d8296104c4d42c',
    messagingSenderId: '285056131909',
    projectId: 'edupro-app-daa1b',
    storageBucket: 'edupro-app-daa1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBY8QbyGTq76A9BCmhjCRQz_infa-GMPU',
    appId: '1:285056131909:ios:1e3762d7d8296104c4d42c',
    messagingSenderId: '285056131909',
    projectId: 'edupro-app-daa1b',
    storageBucket: 'edupro-app-daa1b.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKjsgxNOKHSrH_8LoY2x5IiZaLk2oh0rk',
    appId: '1:285056131909:web:0e0de2860fbe25a8c4d42c',
    messagingSenderId: '285056131909',
    projectId: 'edupro-app-daa1b',
    authDomain: 'edupro-app-daa1b.firebaseapp.com',
    storageBucket: 'edupro-app-daa1b.firebasestorage.app',
    measurementId: 'G-LWYCS8N9ED',
  );
}
